---
title: '#Biofilm NMDS by enclosure status and developmental stage'
author: "Sven Tobias-Hunefeldt"
date: "27/03/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Set up
Import data and refine as done using the set up script

```{r load packages}

library(ggpubr)
library(ggplot2)
library(Rmisc)
library(vegan)
library(phyloseq)


```
```{r Refine colours and shapes}
#Refine colours
cbbPalette <- c("black",
                "red",
                "navy", 
                "green", 
                "magenta",
                "forestgreen",
                "turquoise")

Mesh_Palette = c("Enclosed" = "#000000",
                 "Non-enclosed" = "#E69F00")

Time_colour_list = c("0" = "turquoise", 
                     "7" = "forestgreen", 
                     "14" = "black", 
                     "19" = "red", 
                     "28" = "navy", 
                     "42" = "green", 
                     "56" = "magenta")

#Refine shape list
Substrate_shape_list = c("Acryl" = 15, #Filled square 
                         "Glass" = 16, #Filled circle
                         "Tile" = 17, #Filled Triangle
                         "Pine" = 5, #Hollow diamond
                         "Water" = 11) #Lined star
#Make colour lists
Substrate_colour_list = c("Acryl" = "black",
                  "Glass" = "green",
                  "Tile" = "blue",
                  "Pine" = "magenta")

```
#Recolour Figure 3 F
```{r}
#Get pristine phyloseq object from back up
Phyloseq_Biofilm_16S = Phyloseq_Biofilm_16S_v0

#Subset to only biofilm samples
Phyloseq_Biofilm_16S_noA = subset_samples(Phyloseq_Biofilm_16S, Project == "Marine_Biofilm" & Sample_type == "Biofilm" & !Substrate == "Water"& !Substrate == "Mesh")

#Convert and reorder time for plotting
sample_data(Phyloseq_Biofilm_16S_noA)$Sample_time<-as.factor(as.character(sample_data(Phyloseq_Biofilm_16S_noA)$Sample_time))
sample_data(Phyloseq_Biofilm_16S_noA)$Sequencing <-as.factor("Prokaryotes")
sample_data(Phyloseq_Biofilm_16S_noA)$Mesh_status = gsub("Exposed", "Native", sample_data(Phyloseq_Biofilm_16S_noA)$Mesh_status)
#sample_data(Phyloseq_Biofilm_16S_noA)$Mesh_status = gsub("Enclosed", "Exclusive", sample_data(Phyloseq_Biofilm_16S_noA)$Mesh_status)

#Calculate ordination matrix based on Bray-Curtis dissimilarity
NMDS.ord_16S_noA <- ordinate(Phyloseq_Biofilm_16S_noA, method = "NMDS", distance = "bray")
#Ensure data is good fit
stressplot(NMDS.ord_16S_noA) #Good stressplot
NMDS.ord_16S_noA #Good level of stress

#Design plot
NMDS_16S_noA = plot_ordination(Phyloseq_Biofilm_16S_noA, 
                             NMDS.ord_16S_noA, 
                             shape = "Mesh_status", 
                             color = "StageofBiofilm"
                             ) + 
  theme(legend.position = "right")+
  stat_ellipse(aes(group = StageofBiofilm, lwd = 1))+
  scale_color_manual("Succession \nstage", values = cbbPalette)+
  scale_shape_manual("Condition", values = c(16, 2))+
  geom_point(aes(size = 6), show.legend = F)+
  facet_grid(. ~ Sequencing)+
  annotate("text", x=-3.5, y=3.25, size = 6, label= paste0("Stress = ", round(NMDS.ord_16S_noA$stress, digits = 3)))+
  guides(colour = guide_legend(order = 1),
         shape = guide_legend(order = 2, override.aes = list(size = 4)),
         size = F)+
  theme_bw()+
  My_Theme
#Inspect plot
NMDS_16S_noA

```
#Recolour Figure 3 G
```{r}
#Get pristine phyloseq object from back up
Phyloseq_Biofilm_18S = Phyloseq_Biofilm_18S_v0

#Subset to only biofilm samples
Phyloseq_Biofilm_18S_noA = subset_samples(Phyloseq_Biofilm_18S, Project == "Marine_Biofilm" & Sample_type == "Biofilm" & !Substrate == "Water"& !Substrate == "Mesh")

#Convert and reorder time for plotting
sample_data(Phyloseq_Biofilm_18S_noA)$Sample_time<-as.factor(as.character(sample_data(Phyloseq_Biofilm_18S_noA)$Sample_time))
sample_data(Phyloseq_Biofilm_18S_noA)$Sequencing <-as.factor("Eukaryotes")
sample_data(Phyloseq_Biofilm_18S_noA)$Mesh_status = gsub("Exposed", "Native", sample_data(Phyloseq_Biofilm_18S_noA)$Mesh_status)
#sample_data(Phyloseq_Biofilm_18S_noA)$Mesh_status = gsub("Encosed", "Exclusive", sample_data(Phyloseq_Biofilm_18S_noA)$Mesh_status)

#Calculate ordination matrix based on Bray-Curtis dissimilarity
NMDS.ord_18S_noA <- ordinate(Phyloseq_Biofilm_18S_noA, method = "NMDS", distance = "bray")
#Ensure data is good fit
stressplot(NMDS.ord_18S_noA) #Good stressplot
NMDS.ord_18S_noA #Good level of stress

#Design plot
NMDS_18S_noA = plot_ordination(Phyloseq_Biofilm_18S_noA, 
                             NMDS.ord_18S_noA, 
                             shape = "Mesh_status", 
                             color = "StageofBiofilm"
                             ) + 
  theme(legend.position = "right")+
  stat_ellipse(aes(group = StageofBiofilm, lwd = 1))+
  scale_color_manual("Succession \nstage", values = cbbPalette)+
  scale_shape_manual("Condition", values = c(16, 2))+
  geom_point(aes(size = 6), show.legend = F)+
  facet_grid(. ~ Sequencing)+
  annotate("text", x=-2.3, y=2, size = 6, label= paste0("Stress = ", round(NMDS.ord_18S_noA$stress, digits = 3)))+
  guides(colour = guide_legend(order = 1),
         shape = guide_legend(order = 2, override.aes = list(size = 4)),
         size = F)+
  theme_bw()+
  My_Theme
#Inspect plot
NMDS_18S_noA

```
#Generate combined plots
```{r}
#Make plot
SupplementaryFigure4ms = ggarrange(NMDS_16S_noA,
                                 NMDS_18S_noA,
                                 common.legend = T,
                                 legend = "right",
                                 nrow = 1,
                                 labels = c("AUTO"),
                                 align = "hv")
#Inspect
SupplementaryFigure4ms

#Save plot
tiff("/YOUR/PATH/HERE/Figures_Tables/SupplementaryFigure7ms_BiofilmEnclosureNMDS.tiff", width = 16, height = 6.66, units = "in", res = 300)
SupplementaryFigure4ms
dev.off()

```

